// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestaurant.Data;

namespace MyRestaurant.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20180825135400_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyRestaurant.Data.Entities.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<float>("Price");

                    b.Property<bool>("Promotion");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("MyRestaurant.Data.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Cancel");

                    b.Property<DateTime?>("CloseDate");

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("MenuIdID");

                    b.Property<float>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("UserSignID");

                    b.HasKey("ID");

                    b.HasIndex("MenuIdID");

                    b.HasIndex("UserSignID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MyRestaurant.Data.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(34);

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MyRestaurant.Data.Entities.Order", b =>
                {
                    b.HasOne("MyRestaurant.Data.Entities.Menu", "MenuId")
                        .WithMany()
                        .HasForeignKey("MenuIdID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyRestaurant.Data.Entities.User", "UserSign")
                        .WithMany()
                        .HasForeignKey("UserSignID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
