name: Dotnet build CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.x', '8.x'] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build RestaurantOrderManager.Data
      run: |
        cd RestaurantOrderManager.Data
        dotnet build --configuration Release

    - name: Build RestaurantOrderManager.API
      run: |
        cd RestaurantOrderManager.API
        dotnet build --configuration Release

    - name: Build MyRestaurant.Client
      run: |
        cd MyRestaurant.Client
        dotnet build --configuration Release
